artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/sathyasugee/Dataset_upload/raw/refs/heads/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion.zip
  unzip_dir : artifacts/data_ingestion 

  