artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/sathyasugee/Dataset_upload/raw/refs/heads/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion.zip
  unzip_dir : artifacts/data_ingestion 


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]
  DATA_DIR: artifacts/data_ingestion/samsum_dataset
  

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


model_trainer:
  root_dir : /home/suganya/Documents/Text-Summarization-Project/artifacts/model_trainer
  data_path : /home/suganya/Documents/Text-Summarization-Project/artifacts/data_transformation/samsum_dataset
  model_ckpt : google/pegasus-cnn_dailymail


model_evalution:
  root_dir : artifacts/model_evalution
  data_path : artifacts/data_transformation/samsum_dataset
  model_path : artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path : artifacts/model_trainer/tokenizer
  metrics_file_name : artifacts/model_evalution/metrics.csv

