artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/sathyasugee/Dataset_upload/raw/refs/heads/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion.zip
  unzip_dir : artifacts/data_ingestion 


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]
  DATA_DIR: artifacts/data_ingestion/samsum_dataset
  